schema_version: 1

context:
  version: "0.26"
  lib_major_version: "${{ (version | split('.'))[0] }}"
  build: 3

recipe:
  name: libiio-split
  version: ${{ version }}

source:
  url: https://github.com/analogdevicesinc/libiio/archive/v${{ version }}.tar.gz
  sha256: fb445fb860ef1248759f45d4273a4eff360534480ec87af64c6b8db3b99be7e5

build:
  number: ${{ build }}

outputs:
  - staging:
      name: libiio-build
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - pkg-config
      host:
        - if: linux
          then: bison
        - if: linux
          then: flex
        - if: linux
          then: libaio
        - libusb >=1
        - libxml2-devel
        - zstd

  - package:
      name: libiio-c
    inherit:
      from: libiio-build
      run_exports: false
    build:
      files:
        include:
          - if: linux
            then: lib/libiio.so.${{ lib_major_version }}*
          - if: osx
            then: lib/libiio.${{ lib_major_version }}*.dylib
          - if: win
            then: Library/bin/libiio.dll
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
      host:
        - libusb >=1
        - libxml2-devel
        - zstd
    tests:
      - package_contents:
          strict: true
          files:
            - if: linux
              then: lib/libiio.so.${{ lib_major_version }}*
            - if: osx
              then: lib/libiio.${{ lib_major_version }}*.dylib
            - if: win
              then: Library/bin/libiio.dll
      - downstream: libm2k

  - package:
      name: libiio-devel
    inherit:
      from: libiio-build
      run_exports: false
    build:
      files:
        include:
          - ${{ "Library/" if win }}include/**
          - ${{ "Library/" if win }}lib/**
        exclude:
          - if: linux
            then: lib/libiio.so.*
          - if: osx
            then: lib/libiio.*.dylib
          - if: linux
            then: lib/udev/**
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
      run:
        - ${{ pin_subpackage("libiio-c", exact=True) }}
      run_exports:
        - ${{ pin_subpackage("libiio-c", upper_bound="x") }}
    tests:
      - package_contents:
          strict: true
          include:
            - iio.h
          lib:
            - if: unix
              then: iio
          files:
            - if: win
              then: Library/lib/libiio.lib
            - ${{ "Library/" if win }}lib/pkgconfig/libiio.pc

  - package:
      name: pylibiio
    build:
      string: py_${{ build }}
      noarch: python
      script:
        file: ${{ "build_pylibiio.sh" if not win else "build_pylibiio.bat" }}
    requirements:
      build:
        - cmake
        - ninja
        # cross-compilation dependencies
        - if: build_platform != target_platform
          then: python ${{ python_min }}.*
        - if: build_platform != target_platform
          then: cross-python_${{ target_platform }}
      host:
        - ${{ pin_subpackage("libiio-devel", exact=True) }}
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - libiio-c ${{ version }}.*
        # need libiio-devel dependency because Python bindings search
        # for the library using the unversioned name
        - libiio-devel ${{ version }}.*
        - python >=${{ python_min }}
    tests:
      - python:
          imports:
            - iio
          pip_check: false
          python_version:
            - ${{ python_min }}.*
            - "*"
      - downstream: pyadi-iio

  - package:
      name: libiio
    inherit:
      from: libiio-build
      run_exports: false
    build:
      files:
        include:
          - ${{ "Library/" if win }}bin/**
          - if: linux
            then: lib/udev/**
        exclude:
          - if: win
            then: Library/bin/libiio.dll
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
      host:
        - if: linux
          then: libaio
        - ${{ pin_subpackage("libiio-c", exact=True) }}
        # only iiod (Linux-only) ends up linking against zstd
        - if: linux
          then: zstd
      run:
        - ${{ pin_subpackage("libiio-c", exact=True) }}
        # recipes still use this output as a host dependency, so depend on dev
        - ${{ pin_subpackage("libiio-devel", exact=True) }}
        - ${{ pin_subpackage("pylibiio", exact=True) }}
      run_exports:
        - ${{ pin_subpackage("libiio-c", upper_bound="x") }}
    tests:
      - package_contents:
          strict: true
          bin:
            - iio_attr
            - iio_genxml
            - iio_info
            - iio_readdev
            - iio_reg
            - if: unix
              then: iio_stresstest
            - if: linux
              then: iiod
            - iio_writedev
          files:
            - if: linux
              then: bin/.libiio-post-link.sh
            - if: linux
              then: lib/udev/rules.d/90-libiio.rules
      - python:
          imports:
            - iio
          pip_check: false
          python_version:
            - ${{ python_min }}.*
            - "*"
      - script:
          - iio_attr --help
          - iio_genxml --help
          - iio_info --help
          - iio_readdev --help
          - iio_reg --help
          - if: unix
            then: iio_stresstest --help
          - if: linux
            then: iiod --help
          - iio_writedev --help

about:
  license: LGPL-2.1-or-later AND GPL-3.0-or-later
  license_file:
    - COPYING.txt
    - COPYING_GPL.txt
    - if: win
      then: deps/mdns/LICENSE
    - if: win
      then: deps/wingetopt/LICENSE
  summary: Library for interfacing with Linux IIO devices
  description: >
    libiio is used to interface to the Linux Industrial Input/Output (IIO) Subsystem.
    The Linux IIO subsystem is intended to provide support for devices that in some
    sense are analog to digital or digital to analog converters (ADCs, DACs). This
    includes, but is not limited to ADCs, Accelerometers, Gyros, IMUs, Capacitance to
    Digital Converters (CDCs), Pressure Sensors, Color, Light and Proximity Sensors,
    Temperature Sensors, Magnetometers, DACs, DDS (Direct Digital Synthesis), PLLs
    (Phase Locked Loops), Variable/Programmable Gain Amplifiers (VGA, PGA), and RF
    transceivers. You can use libiio natively on an embedded Linux target (local mode),
    or use libiio to communicate remotely to that same target from a host Linux,
    Windows or MAC over USB or Ethernet or Serial.

    Packages include:

      - `libiio-c` contains the library
      - `libiio-devel` contains the development files for compiling against libiio
      - `pylibiio` contains the Python bindings for libiio
      - `libiio` contains command line tools and depends on all of the above

    For Linux users of `libiio`, you will likely want to link the provided udev rule into your system installation in order for the hardware to have the correct permissions:

        sudo ln -s $CONDA_PREFIX/lib/udev/rules.d/90-libiio.rules /etc/udev/rules.d/
        sudo udevadm control --reload
        sudo udevadm trigger

    Then, make sure your user account belongs to the plugdev group in order to be able to access your device:

        sudo usermod -a -G plugdev <user>

    You may have to restart for this change to take effect.
  homepage: https://github.com/analogdevicesinc/libiio
  repository: https://github.com/analogdevicesinc/libiio
  documentation: https://analogdevicesinc.github.io/libiio/

extra:
  feedstock-name: libiio
  recipe-maintainers:
    - ryanvolz
